version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: credo
    versions:
    - "> 1.5.0, < 1.6"
  - dependency-name: ex_doc
    versions:
    - 0.24.0
    - 0.24.1
  - dependency-name: dialyxir
    versions:
    - 1.1.0
